//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugPack
    {
        public int Id { get; set; }
        public int BoughtDrugSuplyId { get; set; }
        public string CoordX { get; set; }
        public string CoordY { get; set; }
        public int Count { get; set; }
        public int Price { get; set; }
    
        public virtual BoughtDrugSuply BoughtDrugSuply { get; set; }
    }
}
