//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionDrugPrice
    {
        public int Id { get; set; }
        public int RegionId { get; set; }
        public int DrugId { get; set; }
        public long CostForUnit { get; set; }
        public int UnitsOfMeasurementId { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual UnitsIOfMeasurement UnitsIOfMeasurement { get; set; }
        public virtual Region Region { get; set; }
    }
}
